### ISSUE TITLE
Dev Support epic

### ISSUE THREAD

**Issue by corinagum** [microsoft/teams-sdk#453]
This epic should have an updated task list of current dev support items that can't be tracked via the [dev support label](https://github.com/microsoft/teams-ai/labels/dev%20support)
```[tasklist]
### Tasks
- [x] https://github.com/microsoft/teams-ai/discussions/460 - Kavin
- [x] https://github.com/microsoft/teams-ai/discussions/438 - Corina, Chaoyi
- [x] https://github.com/microsoft/teams-ai/discussions/337 Alex, Steve
- [x] https://github.com/microsoft/teams-ai/discussions/467 - Corina
- [x] https://teams.microsoft.com/l/message/19:1380d0074c954998bdd311d02bc9ac3f@thread.skype/1692880430471?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=e6142543-e676-4276-8555-6232b0e3a89f&parentMessageId=1692880430471&teamName=Teams Developer Questions&channelName=Bots&createdTime=1692880430471 - Corina
- [x] https://teams.microsoft.com/l/message/19:1380d0074c954998bdd311d02bc9ac3f@thread.skype/1693010722328?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=e6142543-e676-4276-8555-6232b0e3a89f&parentMessageId=1693010722328&teamName=Teams Developer Questions&channelName=Bots&createdTime=1693010722328 - Corina (Resolved because they never got back to us)
- [ ] https://teams.microsoft.com/l/message/19:1380d0074c954998bdd311d02bc9ac3f@thread.skype/1693328972514?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=e6142543-e676-4276-8555-6232b0e3a89f&parentMessageId=1693328972514&teamName=Teams%20Developer%20Questions&channelName=Bots&createdTime=1693328972514 - Kavin
- [x] https://github.com/microsoft/teams-ai/discussions/528 - Corina
- [x] https://github.com/microsoft/teams-ai/discussions/638?converting=1 - Corina
- [x] https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/3107285 - Corina
- [x] Danny Garber issue with Message Extension - Corina
- [ ] RAG sample - Kavin - https://teams.microsoft.com/l/message/19:skypespaces_7a22628e03004b86b5735b7bb72c0fd3@thread.skype/1698993767639?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=af55e84c-dc67-4e48-9005-86e0b07272f9&parentMessageId=1698993767639&teamName=Microsoft%20Teams&channelName=Bots&createdTime=1698993767639
- [ ] https://github.com/microsoft/teams-ai/issues/539
- [ ] https://github.com/microsoft/teams-ai/pull/947
- [x] Discuss release documentation with Carter - Corina
- [x] Help Ryan N. with deployment/publishing - Corina
- [x] https://github.com/microsoft/teams-ai/discussions/1198 - Corina
- [x] https://github.com/microsoft/teams-ai/discussions/1560 - Corina
- [x] https://github.com/microsoft/teams-ai/discussions/1745 - Corina
- [x] https://github.com/microsoft/teams-ai/discussions/1573 - Corina
- [x] https://github.com/microsoft/teams-ai/discussions/1523 - Corina/Steve
- [x] Danny Garber + handoff not being triggerd - discussing in chat - Corina & Alex
- [x] https://github.com/microsoft/teams-ai/discussions/1780 - Corina
- [x] OYD sample support for Aravind (in Teams) - Lily and Corina
- [ ] https://github.com/microsoft/teams-ai/discussions/1809 - Corina
- [x] Citations for MCS - Corina in Teams
- [x] Python Socket Connection with Swathi Patti - Lily in Teams
```
